#!/bin/bash

# Screenshot guide for ImageDiffTool
# This script helps create and add screenshots to the README

echo "📸 ImageDiffTool Screenshot Guide"
echo "================================"
echo ""
echo "To add a screenshot to your README:"
echo ""
echo "1. Take a screenshot of the running app:"
echo "   - Launch ImageDiffTool"
echo "   - Position the window nicely"
echo "   - Press Cmd+Shift+4 and select the app window"
echo "   - Or press Cmd+Shift+4 then Spacebar to capture the entire window"
echo ""
echo "2. Save the screenshot as 'screenshot.png' in this directory:"
echo "   $(pwd)"
echo ""
echo "3. The README.md already references 'screenshot.png' in the image link"
echo ""
echo "Current README image reference:"
echo "![Image Diff Tool Screenshot](screenshot.png)"
echo ""
echo "📱 Screenshot should show:"
echo "   ✓ Main app window with dark theme"
echo "   ✓ Left and Right panels clearly visible"
echo "   ✓ Drop zones with icons and text"
echo "   ✓ Mode buttons (Side by Side, Overlay, Difference)"
echo "   ✓ Control buttons (Compare, Export, Clear)"
echo "   ✓ File path areas at the top"
echo ""
echo "🎯 For best results:"
echo "   - Use a clean desktop background"
echo "   - Ensure good contrast"
echo "   - Capture at retina resolution if possible"
echo "   - Keep the window at a reasonable size (not too small)"